INSERT INTO DRONE (ID, SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY,STATE) VALUES (1, '0001','Lightweight',12.5,50,'IDLE');

INSERT INTO MEDICATION(ID,NAME,WEIGHT,CODE,IMAGE)VALUES (1,'ABC',10.4,'1111','/file' )
