INSERT INTO DRONE (ID, SERIAL_NUMBER,MODEL,WEIGHT_LIMIT,BATTERY_CAPACITY,STATE,IS_ACTIVE) VALUES (1, '0001','Lightweight',12.5,50,'IDLE',1);

INSERT INTO MEDICATION(ID,NAME,WEIGHT,CODE,IMAGE)VALUES (1,'ABC',10.4,'1111','/file')
