CREATE TABLE DRONE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SERIAL_NUMBER INT NOT NULL ,
    MODEL VARCHAR(255) NOT NULL ,
    WEIGHT DECIMAL NOT NULL ,
    BATTERY_CAPACITY DECIMAL NOT NULL ,
    STATE VARCHAR(255) NOT NULL

);

CREATE TABLE MEDICATION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL ,
    WEIGHT DECIMAL NOT NULL ,
    CODE VARCHAR(255) NOT NULL ,
    IMAGE LONGBLOB NOT NULL

);